### ISSUE TITLE
Link to TeX source in the document?

### ISSUE THREAD

**Issue by mjuric** [lsst/lsst-texmf#49]
Would it be possible (and/or a good idea) to add a "Document source" section to our documents, where we'd record where is the document source (e.g., "http://ls.st/lsst/ldm-XXX")? Perhaps just below the "Change Record" section, something like:

![image](https://cloud.githubusercontent.com/assets/620059/26028938/b60a02d4-37de-11e7-90bd-197a15fa9ed7.png)

PS: We could also add a field in docushare for the repo URL and SHA1 of the build.

**Comment by timj** [comment]
I am adding `\setDocUpstreamLocation` and `\setDocUpstreamVersion` in #61.
