### ISSUE TITLE
Sans serif fonts

### ISSUE THREAD

**Issue by mjuric** [lsst/lsst-texmf#6]
A question about Helvetica (is it?) in our LaTeX — there’s something with the font that makes it look unpleasant.

I can’t really put my finger on it, whether it’s the kerning, the line spacing, or the rendering, or something else, it just looks odd. I think line spacing is a part of it — e.g., the author list on the front page of https://lse-163.lsst.io/v/dmsr-refresh/dpdd.pdf seems all squished?

Question: can we teach our LaTeX style to use Cambria (\usepackage{fontspec} \setmainfont{Cambria} \setmathfont{Cambria Math})? I think that would make these docs nearly identical to their Word counterparts.

(n.b. I personally don't mind the good old 'Computer Modern'...)

**Comment by timj** [comment]
I don't really care all that much about the font but the project clearly prefers sans serif so I picked a sans serif font. I'm happy to switch to any other sans serif font. I'll try your suggestion.

**Comment by timj** [comment]
`fontspec` seems to require `xelatex`. Are we okay with requiring that?

**Comment by timj** [comment]
How are we expecting people to obtain `Cambria` and `Cambria Math`? They also have serifs so if we are going to require a Microsoft font we should use the official project font of `Calibri` (but there is no math font). These are all Microsoft fonts and require Office to be installed. This is going to cause problems in general (you can find the fonts online if you look hard enough and declare that you have bought Office at some point) and makes it impossible to build our documents on Travis.

**Comment by timj** [comment]
Regarding `xelatex` the main problem I've run into (apart from removing packages we no longer need) is that it seems to define `\R` and `\B` and these clash with the versions we use in LSE-163 to indicate new and old text. I would have to use new names in LSE-163 but that's not a deal breaker.

**Comment by timj** [comment]
How about OpenSans (which I seem to be able to get without using `xelatex`)?

**Comment by RobertLuptonTheGood** [comment]
You can use {{\renewcommand}} to override xelatex's commands if we really don't need them (and use {{\let}} to rename the old ones)

**Comment by mjuric** [comment]
Thanks Tim (and sorry to make you work so much -- it's a "nice to have" in the grand scheme of things; I did not mean to turn it into a research project!).

That said:
* OpenSans appears nice (based on 10 seconds of googling). Would it be hard to compile DPDD with it, to see what it looks like?
* I don't quite know what `xelatex` is and how onerous it would be to require it -- I see that `which xelatex` finds it in my `/Library/TeX/texbin/xelatex`, but I don't know how it got there :). Does it come with standard Linux distributions? Would it force me to stop using `pdflatex`? Deferring to *TeX experts!

**Comment by timj** [comment]
I knew nothing until yesterday, but `xelatex` seems to be a modern unicode-aware latex that can understand system fonts. It seems to be pretty standard and you can `latexmk -xelatex` for example. I'll see if I can hack up a OpenSans DPDD for you.

**Comment by timj** [comment]
In #8 I have a PR that switches to OpenSans. I am able to build DPDD using that without using `xelatex`. I'll mail you a copy.
