### ISSUE TITLE
missing/incorrect citation to PSTN-053

### ISSUE THREAD

**Issue by fedhere** [lsst/lsst-texmf#668]
The current github version is missing this citation in the lsst.bib 

@DocuShare{PSTN-053,
   author = {{Rubin’s Survey Cadence Optimization Committee}},
    title = "{Survey Cadence Optimization Committee’s Phase 1 Recommendation}",
     year = 2022,
    month = apr,
   handle = {PSTN-053},
     note = {{Vera C. Rubin Observatory Project Science Technical Note}},
      url = {https://pstn-053.lsst.io/} }

I do have it on a local version however, but the author is "Ivezić" (as it appeared in the PSTN-053 initially) this however has been corrected and the authors are now correctly the whole SCOC, as reported above

**Comment by womullan** [comment]
checking

**Comment by womullan** [comment]
Jonathan fixed it
